/** Identity work. 12 projects, 342 images. Ported verbatim; asset paths remapped. */

export interface IdentityProject {
  src: string;
  name: string;
  slug: string;
  folder: string;
  description?: string;
  imageCount: number;
}

export const identityProjects: IdentityProject[] = [
  { src: "/media/identity/arus/hero.webp", name: "ARUS", slug: "arus", folder: "ARUS", description: "Supermarket in Eatern Europe", imageCount: 11 },
  { src: "/media/identity/assetlab/hero.webp", name: "AssetLab", slug: "assetlab", folder: "AssetLab", description: "Financial services brand", imageCount: 15 },
  { src: "/media/identity/crowd0/hero.webp", name: "Crowd0", slug: "crowd0", folder: "Crowd0", description: "NFT crowd-sourcing platform", imageCount: 52 },
  { src: "/media/identity/farrago/hero.webp", name: "Farrago", slug: "farrago", folder: "Farrago", description: "Creative music agency", imageCount: 51 },
  { src: "/media/identity/nextdistrict/hero.webp", name: "NextDistrict", slug: "nextdistrict", folder: "NextDistrict", description: "NFT sales", imageCount: 28 },
  { src: "/media/identity/onlyone/hero.webp", name: "OnlyOne", slug: "onlyone", folder: "OnlyOne", description: "All-in-one drinks brand", imageCount: 70 },
  { src: "/media/identity/slink/hero.webp", name: "SLINK", slug: "slink", folder: "SLINK", description: "Networking app", imageCount: 12 },
  { src: "/media/identity/vineme/hero.webp", name: "VineMe", slug: "vineme", folder: "VineMe", description: "Christian social media app", imageCount: 27 },
  { src: "/media/identity/artems-gym/hero.webp", name: "Artems Gym", slug: "artems-gym", folder: "artems-gym", description: "Australian gym", imageCount: 12 },
  { src: "/media/identity/olive-and-co/hero.webp", name: "Olive & Co", slug: "olive-and-co", folder: "olive-and-co", description: "Table scaping duo", imageCount: 16 },
  { src: "/media/identity/rachael-perry/hero.webp", name: "Rachael Perry", slug: "rachael-perry", folder: "rachael-perry", description: "Personal fashion brand", imageCount: 10 },
  { src: "/media/identity/thoulstonepark/hero.webp", name: "Thoulstone Park", slug: "thoulstone-park", folder: "thoulstonePark", description: "Community and wellbeing farmshop", imageCount: 39 },
];

export const identityProjectImages: Record<string, string[]> = {
  arus: [
    "/media/identity/arus/hero.webp",
    "/media/identity/arus/arus-images1.webp",
    "/media/identity/arus/arus-images2.webp",
    "/media/identity/arus/arus-images3.webp",
    "/media/identity/arus/arus-images4.webp",
    "/media/identity/arus/arus-images6.webp",
    "/media/identity/arus/arus-images7.webp",
    "/media/identity/arus/arus-images8.webp",
    "/media/identity/arus/arus-images9.webp",
    "/media/identity/arus/arus-images10.webp",
    "/media/identity/arus/arus-images11.webp",
  ],
  assetlab: [
    "/media/identity/assetlab/hero.webp",
    "/media/identity/assetlab/assetlab-images1.webp",
    "/media/identity/assetlab/assetlab-images2.webp",
    "/media/identity/assetlab/assetlab-images3.webp",
    "/media/identity/assetlab/assetlab-images4.webp",
    "/media/identity/assetlab/assetlab-images5.webp",
    "/media/identity/assetlab/assetlab-images6.webp",
    "/media/identity/assetlab/assetlab-images8.webp",
    "/media/identity/assetlab/assetlab-images9.webp",
    "/media/identity/assetlab/assetlab-images10.webp",
    "/media/identity/assetlab/assetlab-images11.webp",
    "/media/identity/assetlab/assetlab-images12.webp",
    "/media/identity/assetlab/assetlab-images13.webp",
    "/media/identity/assetlab/assetlab-images14.webp",
    "/media/identity/assetlab/assetlab-images15.webp",
  ],
  crowd0: [
    "/media/identity/crowd0/hero.webp",
    "/media/identity/crowd0/crowd0-images2.webp",
    "/media/identity/crowd0/crowd0-images3.webp",
    "/media/identity/crowd0/crowd0-images4.webp",
    "/media/identity/crowd0/crowd0-images5.webp",
    "/media/identity/crowd0/crowd0-images6.webp",
    "/media/identity/crowd0/crowd0-images7.webp",
    "/media/identity/crowd0/crowd0-images8.webp",
    "/media/identity/crowd0/crowd0-images9.webp",
    "/media/identity/crowd0/crowd0-images14.webp",
    "/media/identity/crowd0/crowd0-images16.webp",
    "/media/identity/crowd0/crowd0-images23.webp",
    "/media/identity/crowd0/crowd0-images35.webp",
    "/media/identity/crowd0/crowd0-images36.webp",
    "/media/identity/crowd0/crowd0-images37.webp",
    "/media/identity/crowd0/crowd0-images39.webp",
    "/media/identity/crowd0/crowd0-images41.webp",
    "/media/identity/crowd0/crowd0-images42.webp",
    "/media/identity/crowd0/crowd0-images43.webp",
    "/media/identity/crowd0/crowd0-images46.webp",
    "/media/identity/crowd0/crowd0-images47.webp",
    "/media/identity/crowd0/crowd0-images48.webp",
    "/media/identity/crowd0/crowd0-images49.webp",
    "/media/identity/crowd0/crowd0-images51.webp",
    "/media/identity/crowd0/crowd0-images52.webp",
    "/media/identity/crowd0/crowd0-images53.webp",
    "/media/identity/crowd0/crowd0-images54.webp",
    "/media/identity/crowd0/crowd0-images55.webp",
    "/media/identity/crowd0/crowd0-images56.webp",
    "/media/identity/crowd0/crowd0-images57.webp",
    "/media/identity/crowd0/crowd0-images58.webp",
    "/media/identity/crowd0/crowd0-images59.webp",
    "/media/identity/crowd0/crowd0-images60.webp",
    "/media/identity/crowd0/crowd0-images61.webp",
    "/media/identity/crowd0/crowd0-images62.webp",
    "/media/identity/crowd0/crowd0-images63.webp",
    "/media/identity/crowd0/crowd0-images64.webp",
    "/media/identity/crowd0/crowd0-images65.webp",
    "/media/identity/crowd0/crowd0-images66.webp",
    "/media/identity/crowd0/crowd0-images67.webp",
    "/media/identity/crowd0/crowd0-images68.webp",
    "/media/identity/crowd0/crowd0-images69.webp",
    "/media/identity/crowd0/crowd0-images70.webp",
    "/media/identity/crowd0/crowd0-images71.webp",
    "/media/identity/crowd0/crowd0-images72.webp",
    "/media/identity/crowd0/crowd0-images73.webp",
    "/media/identity/crowd0/crowd0-images74.webp",
    "/media/identity/crowd0/crowd0-images75.webp",
    "/media/identity/crowd0/crowd0-images76.webp",
    "/media/identity/crowd0/crowd0-images77.webp",
    "/media/identity/crowd0/crowd0-images78.webp",
  ],
  farrago: [
    "/media/identity/farrago/hero.webp",
    "/media/identity/farrago/farrago-images1.webp",
    "/media/identity/farrago/farrago-images2.webp",
    "/media/identity/farrago/farrago-images3.webp",
    "/media/identity/farrago/farrago-images4.webp",
    "/media/identity/farrago/farrago-images5.webp",
    "/media/identity/farrago/farrago-images6.webp",
    "/media/identity/farrago/farrago-images7.webp",
    "/media/identity/farrago/farrago-images8.webp",
    "/media/identity/farrago/farrago-images9.webp",
    "/media/identity/farrago/farrago-images10.webp",
    "/media/identity/farrago/farrago-images11.webp",
    "/media/identity/farrago/farrago-images12.webp",
    "/media/identity/farrago/farrago-images13.webp",
    "/media/identity/farrago/farrago-images14.webp",
    "/media/identity/farrago/farrago-images15.webp",
    "/media/identity/farrago/farrago-images16.webp",
    "/media/identity/farrago/farrago-images17.webp",
    "/media/identity/farrago/farrago-images18.webp",
    "/media/identity/farrago/farrago-images19.webp",
    "/media/identity/farrago/farrago-images20.webp",
    "/media/identity/farrago/farrago-images21.webp",
    "/media/identity/farrago/farrago-images22.webp",
    "/media/identity/farrago/farrago-images23.webp",
    "/media/identity/farrago/farrago-images24.webp",
    "/media/identity/farrago/farrago-images25.webp",
    "/media/identity/farrago/farrago-images26.webp",
    "/media/identity/farrago/farrago-images27.webp",
    "/media/identity/farrago/farrago-images28.webp",
    "/media/identity/farrago/farrago-images29.webp",
    "/media/identity/farrago/farrago-images30.webp",
    "/media/identity/farrago/farrago-images31.webp",
    "/media/identity/farrago/farrago-images32.webp",
    "/media/identity/farrago/farrago-images33.webp",
    "/media/identity/farrago/farrago-images34.webp",
    "/media/identity/farrago/farrago-images35.webp",
    "/media/identity/farrago/farrago-images37.webp",
    "/media/identity/farrago/farrago-images38.webp",
    "/media/identity/farrago/farrago-images39.webp",
    "/media/identity/farrago/farrago-images40.webp",
    "/media/identity/farrago/farrago-images42.webp",
    "/media/identity/farrago/farrago-images43.webp",
    "/media/identity/farrago/farrago-images44.webp",
    "/media/identity/farrago/farrago-images45.webp",
    "/media/identity/farrago/farrago-images46.webp",
    "/media/identity/farrago/farrago-images47.webp",
    "/media/identity/farrago/farrago-images48.webp",
    "/media/identity/farrago/farrago-images49.webp",
    "/media/identity/farrago/farrago-images50.webp",
    "/media/identity/farrago/farrago-images51.webp",
    "/media/identity/farrago/farrago-images52.webp",
  ],
  nextdistrict: [
    "/media/identity/nextdistrict/hero.webp",
    "/media/identity/nextdistrict/nextdistrict-images1.webp",
    "/media/identity/nextdistrict/nextdistrict-images2.webp",
    "/media/identity/nextdistrict/nextdistrict-images3.webp",
    "/media/identity/nextdistrict/nextdistrict-images4.webp",
    "/media/identity/nextdistrict/nextdistrict-images5.webp",
    "/media/identity/nextdistrict/nextdistrict-images6.webp",
    "/media/identity/nextdistrict/nextdistrict-images7.webp",
    "/media/identity/nextdistrict/nextdistrict-images8.webp",
    "/media/identity/nextdistrict/nextdistrict-images9.webp",
    "/media/identity/nextdistrict/nextdistrict-images10.webp",
    "/media/identity/nextdistrict/nextdistrict-images11.webp",
    "/media/identity/nextdistrict/nextdistrict-images12.webp",
    "/media/identity/nextdistrict/nextdistrict-images13.webp",
    "/media/identity/nextdistrict/nextdistrict-images14.webp",
    "/media/identity/nextdistrict/nextdistrict-images15.webp",
    "/media/identity/nextdistrict/nextdistrict-images16.webp",
    "/media/identity/nextdistrict/nextdistrict-images17.webp",
    "/media/identity/nextdistrict/nextdistrict-images18.webp",
    "/media/identity/nextdistrict/nextdistrict-images19.webp",
    "/media/identity/nextdistrict/nextdistrict-images20.webp",
    "/media/identity/nextdistrict/nextdistrict-images21.webp",
    "/media/identity/nextdistrict/nextdistrict-images23.webp",
    "/media/identity/nextdistrict/nextdistrict-images24.webp",
    "/media/identity/nextdistrict/nextdistrict-images25.webp",
    "/media/identity/nextdistrict/nextdistrict-images26.webp",
    "/media/identity/nextdistrict/nextdistrict-images27.webp",
    "/media/identity/nextdistrict/nextdistrict-images28.webp",
  ],
  onlyone: [
    "/media/identity/onlyone/hero.webp",
    "/media/identity/onlyone/onlyone-images1.webp",
    "/media/identity/onlyone/onlyone-images2.webp",
    "/media/identity/onlyone/onlyone-images3.webp",
    "/media/identity/onlyone/onlyone-images4.webp",
    "/media/identity/onlyone/onlyone-images5.webp",
    "/media/identity/onlyone/onlyone-images6.webp",
    "/media/identity/onlyone/onlyone-images7.webp",
    "/media/identity/onlyone/onlyone-images8.webp",
    "/media/identity/onlyone/onlyone-images9.webp",
    "/media/identity/onlyone/onlyone-images10.webp",
    "/media/identity/onlyone/onlyone-images11.webp",
    "/media/identity/onlyone/onlyone-images12.webp",
    "/media/identity/onlyone/onlyone-images13.webp",
    "/media/identity/onlyone/onlyone-images14.webp",
    "/media/identity/onlyone/onlyone-images15.webp",
    "/media/identity/onlyone/onlyone-images16.webp",
    "/media/identity/onlyone/onlyone-images17.webp",
    "/media/identity/onlyone/onlyone-images18.webp",
    "/media/identity/onlyone/onlyone-images19.webp",
    "/media/identity/onlyone/onlyone-images20.webp",
    "/media/identity/onlyone/onlyone-images21.webp",
    "/media/identity/onlyone/onlyone-images22.webp",
    "/media/identity/onlyone/onlyone-images23.webp",
    "/media/identity/onlyone/onlyone-images24.webp",
    "/media/identity/onlyone/onlyone-images25.webp",
    "/media/identity/onlyone/onlyone-images26.webp",
    "/media/identity/onlyone/onlyone-images27.webp",
    "/media/identity/onlyone/onlyone-images28.webp",
    "/media/identity/onlyone/onlyone-images29.webp",
    "/media/identity/onlyone/onlyone-images30.webp",
    "/media/identity/onlyone/onlyone-images31.webp",
    "/media/identity/onlyone/onlyone-images32.webp",
    "/media/identity/onlyone/onlyone-images33.webp",
    "/media/identity/onlyone/onlyone-images34.webp",
    "/media/identity/onlyone/onlyone-images35.webp",
    "/media/identity/onlyone/onlyone-images36.webp",
    "/media/identity/onlyone/onlyone-images37.webp",
    "/media/identity/onlyone/onlyone-images38.webp",
    "/media/identity/onlyone/onlyone-images39.webp",
    "/media/identity/onlyone/onlyone-images40.webp",
    "/media/identity/onlyone/onlyone-images41.webp",
    "/media/identity/onlyone/onlyone-images43.webp",
    "/media/identity/onlyone/onlyone-images44.webp",
    "/media/identity/onlyone/onlyone-images45.webp",
    "/media/identity/onlyone/onlyone-images46.webp",
    "/media/identity/onlyone/onlyone-images47.webp",
    "/media/identity/onlyone/onlyone-images48.webp",
    "/media/identity/onlyone/onlyone-images49.webp",
    "/media/identity/onlyone/onlyone-images50.webp",
    "/media/identity/onlyone/onlyone-images51.webp",
    "/media/identity/onlyone/onlyone-images52.webp",
    "/media/identity/onlyone/onlyone-images53.webp",
    "/media/identity/onlyone/onlyone-images54.webp",
    "/media/identity/onlyone/onlyone-images55.webp",
    "/media/identity/onlyone/onlyone-images56.webp",
    "/media/identity/onlyone/onlyone-images57.webp",
    "/media/identity/onlyone/onlyone-images58.webp",
    "/media/identity/onlyone/onlyone-images59.webp",
    "/media/identity/onlyone/onlyone-images60.webp",
    "/media/identity/onlyone/onlyone-images61.webp",
    "/media/identity/onlyone/onlyone-images62.webp",
    "/media/identity/onlyone/onlyone-images63.webp",
    "/media/identity/onlyone/onlyone-images64.webp",
    "/media/identity/onlyone/onlyone-images65.webp",
    "/media/identity/onlyone/onlyone-images66.webp",
    "/media/identity/onlyone/onlyone-images67.webp",
    "/media/identity/onlyone/onlyone-images68.webp",
    "/media/identity/onlyone/onlyone-images70.webp",
  ],
  slink: [
    "/media/identity/slink/hero.webp",
    "/media/identity/slink/slink-images1.webp",
    "/media/identity/slink/slink-images2.webp",
    "/media/identity/slink/slink-images3.webp",
    "/media/identity/slink/slink-images4.webp",
    "/media/identity/slink/slink-images5.webp",
    "/media/identity/slink/slink-images6.webp",
    "/media/identity/slink/slink-images7.webp",
    "/media/identity/slink/slink-images9.webp",
    "/media/identity/slink/slink-images10.webp",
    "/media/identity/slink/slink-images11.webp",
    "/media/identity/slink/slink-images12.webp",
  ],
  vineme: [
    "/media/identity/vineme/hero.webp",
    "/media/identity/vineme/vineme-images1.webp",
    "/media/identity/vineme/vineme-images2.webp",
    "/media/identity/vineme/vineme-images3.webp",
    "/media/identity/vineme/vineme-images4.webp",
    "/media/identity/vineme/vineme-images5.webp",
    "/media/identity/vineme/vineme-images6.webp",
    "/media/identity/vineme/vineme-images7.webp",
    "/media/identity/vineme/vineme-images8.webp",
    "/media/identity/vineme/vineme-images10.webp",
    "/media/identity/vineme/vineme-images11.webp",
    "/media/identity/vineme/vineme-images12.webp",
    "/media/identity/vineme/vineme-images13.webp",
    "/media/identity/vineme/vineme-images14.webp",
    "/media/identity/vineme/vineme-images15.webp",
    "/media/identity/vineme/vineme-images16.webp",
    "/media/identity/vineme/vineme-images17.webp",
    "/media/identity/vineme/vineme-images18.webp",
    "/media/identity/vineme/vineme-images19.webp",
    "/media/identity/vineme/vineme-images20.webp",
    "/media/identity/vineme/vineme-images21.webp",
    "/media/identity/vineme/vineme-images22.webp",
    "/media/identity/vineme/vineme-images23.webp",
    "/media/identity/vineme/vineme-images24.webp",
    "/media/identity/vineme/vineme-images25.webp",
    "/media/identity/vineme/vineme-images26.webp",
    "/media/identity/vineme/vineme-images27.webp",
  ],
  "artems-gym": [
    "/media/identity/artems-gym/hero.webp",
    "/media/identity/artems-gym/artemsgym-images1.webp",
    "/media/identity/artems-gym/artemsgym-images2.webp",
    "/media/identity/artems-gym/artemsgym-images3.webp",
    "/media/identity/artems-gym/artemsgym-images4.webp",
    "/media/identity/artems-gym/artemsgym-images5.webp",
    "/media/identity/artems-gym/artemsgym-images6.webp",
    "/media/identity/artems-gym/artemsgym-images7.webp",
    "/media/identity/artems-gym/artemsgym-images8.webp",
    "/media/identity/artems-gym/artemsgym-images9.webp",
    "/media/identity/artems-gym/artemsgym-images11.webp",
    "/media/identity/artems-gym/artemsgym-images12.webp",
  ],
  "olive-and-co": [
    "/media/identity/olive-and-co/hero.webp",
    "/media/identity/olive-and-co/oliveco-images1.webp",
    "/media/identity/olive-and-co/oliveco-images2.webp",
    "/media/identity/olive-and-co/oliveco-images3.webp",
    "/media/identity/olive-and-co/oliveco-images4.webp",
    "/media/identity/olive-and-co/oliveco-images5.webp",
    "/media/identity/olive-and-co/oliveco-images7.webp",
    "/media/identity/olive-and-co/oliveco-images8.webp",
    "/media/identity/olive-and-co/oliveco-images9.webp",
    "/media/identity/olive-and-co/oliveco-images10.webp",
    "/media/identity/olive-and-co/oliveco-images11.webp",
    "/media/identity/olive-and-co/oliveco-images12.webp",
    "/media/identity/olive-and-co/oliveco-images13.webp",
    "/media/identity/olive-and-co/oliveco-images14.webp",
    "/media/identity/olive-and-co/oliveco-images15.webp",
    "/media/identity/olive-and-co/oliveco-images16.webp",
  ],
  "rachael-perry": [
    "/media/identity/rachael-perry/hero.webp",
    "/media/identity/rachael-perry/rachelperry-images2.webp",
    "/media/identity/rachael-perry/rachelperry-images3.webp",
    "/media/identity/rachael-perry/rachelperry-images4.webp",
    "/media/identity/rachael-perry/rachelperry-images51.webp",
    "/media/identity/rachael-perry/rachelperry-images6.webp",
    "/media/identity/rachael-perry/rachelperry-images7.webp",
    "/media/identity/rachael-perry/rachelperry-images8.webp",
    "/media/identity/rachael-perry/rachelperry-images9.webp",
    "/media/identity/rachael-perry/rachelperry-images10.webp",
  ],
  "thoulstone-park": [
    "/media/identity/thoulstonepark/hero.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images1.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images2.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images3.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images4.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images5.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images6.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images7.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images8.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images9.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images10.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images11.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images12.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images13.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images14.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images15.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images16.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images17.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images18.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images19.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images20.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images21.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images22.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images23.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images24.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images25.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images26.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images27.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images28.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images30.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images31.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images32.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images33.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images34.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images35.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images36.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images37.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images38.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images39.webp",
    "/media/identity/thoulstonepark/thoulstone-park-images40.webp",
  ],
};

export const getIdentityProject = (slug: string) => identityProjects.find((p) => p.slug === slug);
export const getIdentityImages = (slug: string): string[] => identityProjectImages[slug] ?? [];
