// GENERATED by scripts/build-media.mjs — do not edit by hand.
// Filenames are content-hashed, so changing a source image changes its URL and
// no cache anywhere can serve the previous one.

export const slidePaths = [
  "/media/canon/slide-01.cb341b95.webp",
  "/media/canon/slide-02.50c6e879.webp",
  "/media/canon/slide-03.acbe8d62.webp",
  "/media/canon/slide-04.86690796.webp",
  "/media/canon/slide-05.14807ba0.webp",
  "/media/canon/slide-06.fd558515.webp",
  "/media/canon/slide-07.c141e2c6.webp",
  "/media/canon/slide-08.978350a3.webp",
  "/media/canon/slide-09.0ae3980c.webp",
  "/media/canon/slide-10.ca6fe8d7.webp",
];

export const tdcIcon = "/media/brand/tdc-icon.c0998598.webp";
