// GENERATED by scripts/crop-portraits.mjs — do not edit by hand.
// Filenames are content-hashed, so changing a source image changes its URL and
// no cache anywhere can serve the previous one.

export const portraits = {
  city: "/media/portrait/hal-city.510e7e86.webp",
  camp: "/media/portrait/hal-camp.0bc233ab.webp",
} as const;
