/**
 * Every generated image, with a content hash in its filename.
 *
 * The portraits were hashed a while back; the slides and brand marks were not,
 * and that asymmetry caused two separate "you're using the wrong image" bugs.
 * Regenerating a file under an unchanged URL changes nothing a reader sees:
 * Next's image optimiser keeps serving the variant it cached against that URL
 * and the browser keeps its own copy. The files were right and every cache in
 * between was wrong.
 *
 * A hash in the name means changing an image changes its URL, so nothing can
 * serve the previous one and nobody has to remember to clear a cache.
 */
import { createHash } from "node:crypto";
import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SLIDES_SRC = "/Users/henrywall/Desktop/EXPORT_AUG_SLIDES/round7/round9_appstore";
const TDC_LOGOS = "/Users/henrywall/Desktop/Claude_Brain/1-apps/tdc/public/logos";

const hash = (buf) => createHash("sha256").update(buf).digest("hex").slice(0, 8);

async function clean(dir, keep = () => false) {
  await mkdir(dir, { recursive: true });
  for (const f of await readdir(dir)) {
    if (!keep(f)) await unlink(path.join(dir, f));
  }
}

// ---- App Store slides -----------------------------------------------------
// Sorted numerically, not lexicographically: a plain sort puts 10 after 1.
await clean("public/media/canon");
const slideFiles = (await readdir(SLIDES_SRC))
  .filter((f) => f.endsWith(".png"))
  .sort((a, b) => parseInt(a) - parseInt(b));

const slides = [];
for (const file of slideFiles) {
  const buf = await sharp(path.join(SLIDES_SRC, file))
    .resize({ width: 1000, withoutEnlargement: true })
    .webp({ quality: 82, effort: 6 })
    .toBuffer();
  const n = String(parseInt(file)).padStart(2, "0");
  const name = `slide-${n}.${hash(buf)}.webp`;
  await writeFile(path.join("public/media/canon", name), buf);
  slides.push({ n, name, from: file });
  console.log(`${file} -> ${name}  ${(buf.length / 1024).toFixed(0)}KB`);
}

// ---- The Daily Canon mark -------------------------------------------------
// logo_green.png is the stacked books. logo_icon_green.png is Long Form Press,
// a different company of Hal's entirely, and was the source of the wrong mark.
const iconBuf = await sharp(path.join(TDC_LOGOS, "logo_green.png"))
  .resize(256, 256, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
  .webp({ quality: 92 })
  .toBuffer();
const iconName = `tdc-icon.${hash(iconBuf)}.webp`;
for (const f of await readdir("public/media/brand")) {
  if (f.startsWith("tdc-icon")) await unlink(path.join("public/media/brand", f));
}
await writeFile(path.join("public/media/brand", iconName), iconBuf);
console.log(`logo_green.png -> ${iconName}`);

await writeFile(
  "content/media.ts",
  `// GENERATED by scripts/build-media.mjs — do not edit by hand.
// Filenames are content-hashed, so changing a source image changes its URL and
// no cache anywhere can serve the previous one.

export const slidePaths = [
${slides.map((s) => `  "/media/canon/${s.name}",`).join("\n")}
];

export const tdcIcon = "/media/brand/${iconName}";
`,
);
console.log("wrote content/media.ts");
